using System.Collections.Immutable;
using System.Text;
using Derive.Generator.Utils;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Derive.Generator
{
    [Generator]
    public class BaseSerializer : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Step 1: Find classes with our marker attribute
            var baseClasses = context
                .SyntaxProvider.CreateSyntaxProvider(
                    predicate: static (node, _) =>
                        node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
                    transform: static (ctx, _) => GetClassInfo(ctx)
                )
                .WhereNotNull();

            IncrementalValueProvider<ImmutableArray<string>> globalUsings =
                DeclarationHelpers.ProvideUsings(context);

            context.RegisterSourceOutput(baseClasses.Combine(globalUsings), Generate);
        }

        private static BaseClassInfo? GetClassInfo(GeneratorSyntaxContext context)
        {
            var classDecl = (ClassDeclarationSyntax)context.Node;

            // Look for an attribute named "Derive"
            var attributes = classDecl
                .AttributeLists.SelectMany(al => al.Attributes)
                .OfAttributeType<BaseAttribute>()
                .ToArray();

            AttributeSyntax attribute;
            switch (attributes.Length)
            {
                case 0:
                    return null;
                case 1:
                    attribute = attributes[0];
                    break;
                default:
                    // TODO: Diagnostics?
                    throw new NotImplementedException("More than one Derive attribute detected");
            }

            if (
                context.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classType
            )
            {
                return null;
            }

            return new(classType, []);
        }

        private static void Generate(
            SourceProductionContext spc,
            (BaseClassInfo, ImmutableArray<string>) tuple
        )
        {
            var (baseInfo, globalUsings) = tuple;
            foreach (var diagnostic in baseInfo.Diagnostics)
            {
                spc.ReportDiagnostic(diagnostic);
            }
            SerializeSourceForBase(spc, baseInfo.Type, globalUsings);
        }

        private static void SerializeSourceForBase(
            SourceProductionContext spc,
            INamedTypeSymbol baseType,
            ImmutableArray<string> globalUsings
        )
        {
            string className = Namings.GetFullMetadataName(baseType);
            string identifier = Namings.GetDeterministicHashIdentifier(className);
            var typeSyntax = baseType.GetTypeSyntax(spc.CancellationToken);
            var root = typeSyntax.SyntaxTree.GetRoot(spc.CancellationToken);
            var fileUsings = root.ChildNodes().OfType<UsingDirectiveSyntax>().ToArray();

            var sb = new StringBuilder();
            foreach (var usingString in globalUsings)
            {
                sb.Append("using ").Append(usingString).Append(';').AppendLine();
            }
            // TODO: should probably use the semantic model for the usings
            foreach (var usingString in fileUsings)
            {
                sb.AppendLine(usingString.ToString());
            }
            sb.AppendLine(typeSyntax.ToFullString());
            spc.AddSource(
                $"{identifier}_source",
                $$"""
// <auto-generated/>
#nullable enable
namespace {{Namings.GeneratedNamespace}}
{
  internal static partial class BaseSources
  {
    // Source of {{className}}
    public const string {{identifier}} = {{SymbolDisplay.FormatLiteral(
                    sb.ToString(),
                    quote: true
                )}};
  }
}
"""
            );
        }

        private sealed record BaseClassInfo(
            INamedTypeSymbol Type,
            ImmutableArray<Diagnostic> Diagnostics
        );
    }
}
